### ISSUE TITLE
Allow access from pages without a password prompt

### ISSUE THREAD

**Issue by jpvantuyl** [perfectapi/ChromeKeePass#13]
I would like to be able to open and browse the db without having to navigate to a page with a password (e.g. http://keepass.info/help/kb/testform.html]) then doing a manual search.  I've got non-website passwords in my db that I like to look at from time to time.

**Comment by DukeyToo** [comment]
Latest code activates on any page with an input - doesn't have to be a password.  This change is intended to help with sites that have username fields on a different page than the password.  

Probably doesn't solve your issue, but makes it a little easier to get to the password dialog.

**Comment by DukeyToo** [comment]
I have created a new repository for this type of functionality - https://github.com/perfectapi/ChromeKeePass-App.  

The chrome extension (this repository) is more applicable to context sensitive operations - a Chrome App will work well for the use case you have described.
