### ISSUE TITLE
Unit tests

### ISSUE THREAD

**Issue by jpvantuyl** [perfectapi/ChromeKeePass#14]
:)

I'd love to see things tested out using your preferred framework.  Actually, I wouldn't mind doing some myself just to explore the code.

**Comment by DukeyToo** [comment]
I am not very experienced with unit-testing JavaScript code.  It would be extremely useful to be able to do so, specially for the decryption scenarios, but what has stymied me so far is how to do it without tripping over the chrome extension apis.   I think it is just a matter of applying some hard work to get bootstrapped, but I have been unable to do that so far.

**Comment by jpvantuyl** [comment]
Fair enough.  I haven't worked with the chrome extension APIs and I've only done a middling amount of JS testing.  I'll take a closer look and see if I can get something off the ground.

**Comment by DukeyToo** [comment]
I have started adding some unit tests, using mocha and shouldjs.
