### ISSUE TITLE
Passwords in subfolders of Keepass db don't show

### ISSUE THREAD

**Issue by jpvantuyl** [perfectapi/ChromeKeePass#16]
I only see passwords in the root folder of my KeePass db.

If I save a password in a subfolder (e.g. Internet) then they don't display in ChromeKeePass for selection.

**Comment by DukeyToo** [comment]
I have not seen this issue.  Can you provide more details?  KDB or KDBX?

**Comment by jpvantuyl** [comment]
KDBX

Looks like I needed to shut down Chrome and come back to it later.  Now I'm
seeing passwords from subfolders.

There might be a caching issue somewhere in there when using local storage
instead of Drive and editing that file in another editor like the Windows
KeePass client.

**Comment by DukeyToo** [comment]
Do you think this may be the same issue as you mentioned in #15 - the local copy is not kept in sync with other storage?

**Comment by jpvantuyl** [comment]
That seems consistent.  I think adding some documentation should be a
sufficient fix.
